new example to show a missing dep in native compilation
to reproduce the bug:
  - compile using `make native`
  - modify the value in `lib/a.ml`
  - do `make native` again

you should see the following error:
```
ocamlbuild -use-ocamlfind -plugin-tag "package(solvuu-build)" ./my_project_lib.cmxa ./my_project_lib2.cmxa ./my_project_lib.cmxs ./my_project_lib2.cmxs
Finished, 0 targets (0 cached) in 00:00:00.
+ ocamlfind ocamlopt -o ./my_project_lib.cmx -pack lib/a.cmx lib/b.cmx
File "./my_project_lib.cmx", line 1:
Error: Files lib/b.cmx and lib/a.cmx
       make inconsistent assumptions over implementation A
Command exited with code 2.
Compilation unsuccessful after building 4 targets (2 cached) in 00:00:00.
_build/project.mk:20 : la recette pour la cible « native » a échouée
make: *** [native] Erreur 10
```